# Generated by Django 3.2 on 2022-12-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='basedomain',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='clientid',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
