# Generated by Django 3.2 on 2022-12-30 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20221226_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='signupuserid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.signup'),
        ),
    ]
